name: Submit a PR to docker-mediawiki repository

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'i18n/**'
    - '.github/**'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - run: |
          curl \
            --fail \
            --request POST \
            --url https://api.github.com/repos/femiwiki/docker-mediawiki/dispatches \
            --header "Authorization: token ${{ secrets.BOT_TOKEN }}" \
            --header 'content-type: application/json' \
            --data '{
              "event_type": "bump-extension",
              "client_payload": {
                "extension": "Femiwiki",
                "version": "${{ github.sha }}"
              }
            }'
